### PR TITLE
Add basic Halloween hunt details

### PR DESCRIPTION
**Pull request by tehhowch**
Enables DB queries to distinguish between hunts with and without firing cannons

example hunt detail object for my horn from Gnawnia Rift with Lockbox Limburger armed:
image

### CODE REVIEW

**Comment by tsitu** [comment]
What are the benefits of tracking those 3 in hunt details?

**Comment by tehhowch** [comment]
AFAIK, you can't determine if the GGG should be dropped since it isn't dropped when the cannon is active.

**Comment by tsitu** [comment]
Oops, had a couple of comments on this that I forgot to share.

First, is getting a precise GGG drop rate worth the effort? I hear the devs are using the global drop mechanic again, which means DR is normalized based on AR and CR (similar to Chrome Bits). This makes things quite a bit trickier to derive.

Second, even if we decide to track GGG drop rate, are the `halloween_hunt` and `in_stockpile` details strictly necessary? The former can be queried for using event start/end timestamps, and the latter we know from in-game information.

**Comment by tsitu** [comment]
@tehhowch

**Comment by tehhowch** [comment]
As far as the utility of those flags, they may make the actual db queries simpler (one doesn't need to remember which locations were stockpiles in which year, nor do the event timestamps need to be included in the query).

One thing that we don't yet know is if the Halloween quest will disappear immediately when the "active" portion of the event ends (probably not), or if it will stick around until the user's spooky aura is consumed, or {{insert other condition}}. 

If the details aren't useful, we can revert the PR

**Pull request merged**
