### PR TITLE
refactor(hunt_details): always perform hunt_details calculations via `addHuntDetails` method

### PR DESCRIPTION
**Pull request by tehhowch**
- move pillage tracking from `createMessageFromHunt` into own method, like lucky catches
 - revert usage of `Object.assign` in location-specific hunt details methods (guaranteed no existing hunt details)
   - fixes bug in Harbour hunt details

Ref #92 #103

### CODE REVIEW

**Comment by AardWolf** [comment]
I don't understand why you moved away from Object.assign - that was added because otherwise the hunt details get overwritten by things - like in claw shot on a poster if the boss pillages the pillage information or poster information would be submitted but not both.

**Comment by tehhowch** [comment]
@AardWolf the flow was previously that a message may not have hunt details. If details were available for a location, they would be created and then any global details would be added.

In the pillage tracking PR, every message was given hunt details by default, so the location-specific details needed to be changed to append to the existing details object, rather than create them.

With this PR, we return to the flow of the former, where not all messages will have hunt details - only those where a location trigger fired, and/or where a global condition was met, such as catching a mouse or being pillaged.

**Comment by tehhowch** [comment]
@AardWolf I updated the logic to make it more clear. We now only set `hunt_details` in a single location, and explicitly merge all details objects that might be present.

**Comment by AardWolf** [comment]
Thank you! It all makes sense to me and looks like it's ready to go.

**Review by AardWolf — APPROVED** [review]

**Pull request merged**
